/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedJuzzRouteImport } from './routes/_authenticated/juzz'
import { Route as AuthenticatedTableauDeBordRouteImport } from './routes/_authenticated/tableau-de-bord'
import { Route as AuthenticatedSouratesIndexRouteImport } from './routes/_authenticated/sourates/index'
import { Route as AuthenticatedSouratesIdRouteImport } from './routes/_authenticated/sourates/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedJuzzRoute = AuthenticatedJuzzRouteImport.update({
  id: '/juzz',
  path: '/juzz',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTableauDeBordRoute =
  AuthenticatedTableauDeBordRouteImport.update({
    id: '/tableau-de-bord',
    path: '/tableau-de-bord',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSouratesIndexRoute =
  AuthenticatedSouratesIndexRouteImport.update({
    id: '/sourates/',
    path: '/sourates/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSouratesIdRoute = AuthenticatedSouratesIdRouteImport.update({
  id: '/sourates/$id',
  path: '/sourates/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/juzz': typeof AuthenticatedJuzzRoute
  '/tableau-de-bord': typeof AuthenticatedTableauDeBordRoute
  '/sourates/$id': typeof AuthenticatedSouratesIdRoute
  '/sourates/': typeof AuthenticatedSouratesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/juzz': typeof AuthenticatedJuzzRoute
  '/tableau-de-bord': typeof AuthenticatedTableauDeBordRoute
  '/sourates/$id': typeof AuthenticatedSouratesIdRoute
  '/sourates': typeof AuthenticatedSouratesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/juzz': typeof AuthenticatedJuzzRoute
  '/_authenticated/tableau-de-bord': typeof AuthenticatedTableauDeBordRoute
  '/_authenticated/sourates/$id': typeof AuthenticatedSouratesIdRoute
  '/_authenticated/sourates/': typeof AuthenticatedSouratesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/juzz'
    | '/tableau-de-bord'
    | '/sourates/$id'
    | '/sourates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/auth' | '/juzz' | '/tableau-de-bord' | '/sourates/$id' | '/sourates'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/juzz'
    | '/_authenticated/tableau-de-bord'
    | '/_authenticated/sourates/$id'
    | '/_authenticated/sourates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/juzz': {
      id: '/_authenticated/juzz'
      path: '/juzz'
      fullPath: '/juzz'
      preLoaderRoute: typeof AuthenticatedJuzzRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tableau-de-bord': {
      id: '/_authenticated/tableau-de-bord'
      path: '/tableau-de-bord'
      fullPath: '/tableau-de-bord'
      preLoaderRoute: typeof AuthenticatedTableauDeBordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sourates/': {
      id: '/_authenticated/sourates/'
      path: '/sourates'
      fullPath: '/sourates/'
      preLoaderRoute: typeof AuthenticatedSouratesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sourates/$id': {
      id: '/_authenticated/sourates/$id'
      path: '/sourates/$id'
      fullPath: '/sourates/$id'
      preLoaderRoute: typeof AuthenticatedSouratesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedJuzzRoute: typeof AuthenticatedJuzzRoute
  AuthenticatedTableauDeBordRoute: typeof AuthenticatedTableauDeBordRoute
  AuthenticatedSouratesIdRoute: typeof AuthenticatedSouratesIdRoute
  AuthenticatedSouratesIndexRoute: typeof AuthenticatedSouratesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedJuzzRoute: AuthenticatedJuzzRoute,
  AuthenticatedTableauDeBordRoute: AuthenticatedTableauDeBordRoute,
  AuthenticatedSouratesIdRoute: AuthenticatedSouratesIdRoute,
  AuthenticatedSouratesIndexRoute: AuthenticatedSouratesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
